app3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls',namespace='todolist'))
]

todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
    path('',view=views.index,name='index'),
    path('add/',view=views.add, name='add'),
    path('update/<int:todo_id>/',view=views.update, name='update'),
    path('delete/<int:todo_id>/',view=views.delete, name='delete')
]

todolist/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField("заголовок",max_length=200)
    is_complete = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = "задача"
        verbose_name_plural = "задачи"

todolist/views.py
from django.shortcuts import render,redirect
from django.views.decorators.http import require_http_methods
from .models import Todo
# Create your views here.

def index(request):
    todolist = Todo.objects.all()
    context = {
        'title':'Главная страница',
        'todolist':todolist
    }
    return render(request, 'todolist/index.html',context)

@require_http_methods(['POST'])
def add(request):
    title=request.POST['title']
    todo = Todo(title=title)
    todo.save()
    return redirect('todolist:index')

def update(request, todo_id):
    try:
        todo = Todo.objects.get(id=todo_id)
        todo.is_complete= not todo.is_complete
        todo.save()
        return redirect('todolist:index')
    except:
        return redirect('todolist:index')
    
def delete(request, todo_id):
    try:
        todo = Todo.objects.get(id=todo_id)
        todo.delete()
        return redirect('todolist:index')
    except:
        return redirect('todolist:index')

todolist/templates/todolist/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
  
    {% endblock content %}
  </div>
</body>
</html>

todolist/templates/todolist/index.html
{% extends "todolist/base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="alert alert-light" role="alert">
<form action="{% url "todolist:add" %}" method="post">
  {% csrf_token %}
  <input type="text" name="title" placeholder="название задачи" class="form-control"><br>
  <button type="submit" class="btn btn-dark">Добавить</button>
</form>
</div>


{% for todo in todolist  %}
<div class="alert alert-light" role="alert">
  <h3>{{ todo.title }}</h3>
  {% if todo.is_complete == False %}
    <label class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">незавершен</label><br><br>
  {% else %}
    <label class="badge bg-success-subtle border border-success-subtle text-success-emphasis rounded-pill">завершен</label><br><br>
  {% endif %}
  <a href="{% url "todolist:update" todo_id=todo.id %}" class="btn btn-outline-primary">закрыть</a>
  <a href="{% url "todolist:delete" todo_id=todo.id %}" class="btn btn-outline-danger">удалить</a>
</div>
{% endfor %}
{% endblock content %}